services:
  client:
    build: ./client
    volumes:
      - ./client/src:/app/src
    ports:
      - 3000:3000
  server:
    build: ./server
    volumes:
      - ./server/src:/app/src
    ports:
      - 5000:5000
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: changemeinprodplease

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
